apiVersion: v1
kind: Service
metadata:
  name: django-svc
spec:
  type: LoadBalancer
  selector:
    app: django-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30321
      protocol: TCP
