apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      restartPolicy: Always
      containers:
      - name: django-app
        image: freeflowcode/k8s-test-django-lesson2:76a9adc
        volumeMounts:
          - mountPath: /root/.postgresql
            name: psql-cert-volume
        ports:
        - containerPort: 80
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: postgres
                key: url
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: django-secret
                key: secret_key
          - name: DEBUG
            valueFrom:
              secretKeyRef:
                name: django-secret
                key: debug
          - name: ALLOWED_HOSTS
            valueFrom:
              secretKeyRef:
                name: django-secret
                key: allowed_hosts
      volumes:
        - name: psql-cert-volume
          secret:
            secretName: postgresql-ssl
            defaultMode: 0600
---
apiVersion: v1
kind: Service
metadata:
  name: django-svc
spec:
  type: LoadBalancer
  selector:
    app: django-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30321
      protocol: TCP
