apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-app
  template:
    metadata:
      labels:
        app: ubuntu-app
    spec:    
      containers:
        - name: ubuntu
          image: ubuntu:22.04
          volumeMounts:
            - mountPath: /root/.postgresql
              name: psql-cert-volume
          env:
            - name: DEBIAN_FRONTEND
              value: noninteractive
            - name: TZ
              value: Europe/Moscow
          command: ["/bin/sh", "-c"]
          args:
            - apt-get update && apt-get install -y postgresql-client;
              sleep infinity; 
          ports:
            - containerPort: 80
      volumes:
        - name: psql-cert-volume
          secret:
            secretName: postgresql-ssl
            defaultMode: 0600
